version: '3.7'
services:
  server:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    links:
      - db
    command: ['npm', 'start']
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dataflow
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./tmp/db:/var/lib/postgresql/data

volumes:
  db-data: {}